### ISSUE TITLE
getWindowOpen and FritzOS 7

### ISSUE THREAD

**Issue by delta2308151984** [andig/fritzapi#8]
I´ve updated my FritzBox 7490 to OS 7.01 and the getWindowOpen function don´t work anymore. It´s just getting false. 

In the example.js Raw devices section it is getting the correct windowopenactiv: 1 state

**Comment by andig** [comment]
That looks like either a UI bug or a functionality change. The table is no longer displaying the window open icon:

<img width="863" alt="screen shot 2018-09-13 at 15 05 31" src="https://user-images.githubusercontent.com/184815/45490089-80305b00-b766-11e8-8344-b7adc8c24452.png">

The raw device output has also changed:

    [ { identifier: '119340326786-1',
        id: '2000',
        functionbitmask: '8208',
        fwversion: '0.0',
        manufacturer: '0x0feb',
        productname: 'HAN-FUN',
        present: '1',
        name: 'no name',
        etsiunitinfo: { etsideviceid: '406', unittype: '514', interfaces: '256' },
        alert: { state: '1' } },
      { identifier: '119340326786',
        id: '406',
        functionbitmask: '1',
        fwversion: '00.00',
        manufacturer: '0x0feb',
        productname: 'HAN-FUN',
        present: '1',
        name: 'HAN-FUN #1' } ]

Instead of the HANFUN device there is now device plus one entry per function.

I'm wondering if this complexity should be hidden in terms of supporting multiple FritzOS versions:

  - try AIN as HAN function first?
  - find window sensor for matching AIN?
  - use UI fallback as last resort?

I'll see if I can draft something.

**Comment by delta2308151984** [comment]
The icon is still shown in the UI.
![smarthome](https://user-images.githubusercontent.com/25320876/45498828-474eb100-b77b-11e8-8870-1b40c7e35eb7.png)

![smarthome_icon](https://user-images.githubusercontent.com/25320876/45498872-5e8d9e80-b77b-11e8-8d4b-e889d35cae21.png)

**Comment by andig** [comment]
So, without adding another API and utilizing lodash you could do something like:

    getDevice(sid, ain).then(device => +_.get(device, ['alert', 'state']));

Would that work for you?

**Comment by delta2308151984** [comment]
Sorry, meine Java Kenntnisse sind nur rudimentär ;-)
Muss ich das in eine neue function einbauen?
Am 13. Sep. 2018, 17:41 +0200 schrieb andig <notifications@github.com>:

**Comment by andig** [comment]
Gegenfrage- wo hast Du es denn überhaupt eingebaut und wie? Dann zeige ich Dir der Einfachheit halber wie das zu verändern wäre.

**Comment by danieltrapp** [comment]
Habe das example.js am Ende angepasst:

var fritz = require('./index.js');

var options = {
"url": "http://fritz.box"
};

var username = „xxx";
var password = „xxx";

fritz.getSessionID(username, password, options).then(function(sid) {

fritz.getWindowOpen(sid, "099950013169").then(function(state) {
if(state == true){console.log("Fenster auf")}
if(state == false){console.log("Fenster zu")}
});
})
.catch(function(error) {
console.log(error);
});

Und das Ergebnis greif ich dann mit einem einfachen script ab:

#!/bin/bash
#sleeptime1 default = 1m
sleeptime1=("1m")
#sleeptime2 default = 6m
sleeptime2=("6m")
ausgabe=$(/usr/local/bin/node /home/pi/fritzapi_neu/node_modules/fritzapi/window-open-bad.js)
if [ "$ausgabe" = "0000000000000000" ]
then
printf "%b\n Fehler: Thermostat Bad nicht erreichbar %b\n\n"
mail -s "Achtung!" xxx@delta23.de <<< "Thermostat Bad nicht erreichbar"
else
if [ -e /tmp/fenster_auf ]
then
printf "%b\n Fenster-auf Erkennung wurde bereits gestartet. %b\n\n"
exit 1
else
if [ "$ausgabe" = "Fenster auf" ]
then
touch /tmp/fenster_auf
stdbuf -o0 printf "%b\n Fenster-auf Erkennung: An. Warten ...%b\n"
stdbuf -o0 printf " 10 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 9 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 8 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 7 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 6 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 5 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 4 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 3 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 2 Minuten"
sleep $sleeptime1;
stdbuf -o0 printf "%s\r"
stdbuf -o0 printf " 1 Minute"
sleep $sleeptime1;

if [ -e /tmp/iphone_daniel_is_home ]
then
curl -s \
--form-string "token=xxx" \
--form-string "user=xxx" \
--form-string "message=Fenster im Bad schließen!" \
--form-string "priority=0" \
--form-string "sound=bike" \
--form-string "device=MacBookAir,iphone-daniel" \
https://api.pushover.net/1/messages.json
fi
if [ -e /tmp/iphone_anne_is_home ]
then
curl -s \
--form-string "token=xxx" \
--form-string "user=xxx" \
--form-string "message=Fenster im Bad schließen!" \
--form-string "priority=0" \
--form-string "sound=bike" \
--form-string "device=iphone-anne" \
https://api.pushover.net/1/messages.json
fi
sleep $sleeptime2;
rm /tmp/fenster_auf
else
printf "%b\n Fenster-auf Erkennung: Aus %b\n\n"
fi
fi
fi

Simpel, aber hat bisher sehr gut funktioniert ;-)
Am 13. Sep. 2018, 18:26 +0200 schrieb andig <notifications@github.com>:

**Comment by andig** [comment]
Autsch ;) Das müsste dann so aussehen:

	fritz.getDevice(sid, '099950013169').then(function(device) {
		var status = +device.alert.state ? "auf" : "zu";
		console.log("Fenster " + status);
	});

**Comment by delta2308151984** [comment]
Leider bekomme ich folgende Fehlermeldung:

Unhandled rejection TypeError: Cannot read property 'state' of undefined
at /home/pi/node_modules/fritzapi/window-open-bad.js:709:34
at tryCatcher (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/promise.js:694:18)
at _drainQueueStep (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/async.js:138:12)
at _drainQueue (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/async.js:131:9)
at Async._drainQueues (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/async.js:147:5)
at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/node_modules/fritzapi/node_modules/bluebird/js/release/async.js:17:14)
at processImmediate [as _immediateCallback] (timers.js:396:17)

**Comment by danieltrapp** [comment]
Hi, ich habe es die letzen Tage immer wieder versucht hinzubekommen. Leider ohne erfolg :(
Vielleicht hast du ja noch mal ein Moment Zeit. Wäre echt super.

Grüße, Daniel
Am 14. Sep. 2018, 17:23 +0200 schrieb Daniel Trapp <danieltrapp@delta23.de>:
